version: '3.7'

services:
  scratchpay-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: scratchpay-docker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev