openapi: 3.0.0
info:
  title: Scratchpay
  version: 0.0.1

paths:
  /clinics:
    get:
      tags:
        - 'clinics'
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum: ['vet', 'dental']
        - name: name
          in: query
          schema:
            type: string
            example: 'Good Health Clinic'
        - name: state
          in: query
          schema:
            type: string
            example: 'CA'
        - name: available_at
          in: query
          schema:
            type: string
            example: '08:00'
      responses:
        200:
          description: List of clinics

components:
  responses:
    BadRequest:
      description: One or more invalid parameters
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'
              - properties:
                    details:
                      type: array
                      description: Validations errors
                      items:
                        type: string
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          description: HTTP status code
        code:
          type: string
          description: System error code
    Clinic:
      type: object
      properties:
        type:
          type: string
          enum: ['dental', 'vet']
        name:
          type: string
        state:
          type: string
        opening:
          type: object
          properties:
            from:
              type: string
              example: '08:00'
            to:
              type: string
              example: '18:00'


