openapi: 3.0.0
info:
  title: Scratchpay
  version: 0.0.1

paths:
  /clinics:
    get:
      tags:
        - 'clinics'
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum: ['vet', 'dental']
        - name: name
          in: query
          schema:
            type: string
            example: 'Good Health Clinic'
        - name: state
          in: query
          schema:
            $ref: '#/components/schemas/State'
        - name: available_at
          in: query
          schema:
            type: string
            example: '08:00'
      responses:
        200:
          description: List of clinics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Clinic'
        400:
          $ref: '#/components/responses/BadRequest'

components:
  responses:
    BadRequest:
      description: One or more invalid parameters
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/Error'
              - properties:
                    details:
                      type: array
                      description: Validations errors
                      items:
                        type: string
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          description: HTTP status code
        code:
          type: string
          description: System error code
    Clinic:
      type: object
      properties:
        name:
          type: string
        state:
          type: string
        opening:
          type: object
          properties:
            from:
              type: string
              example: '08:00'
            to:
              type: string
              example: '18:00'
    State:
      type: string
      enum:
        - AZ
        - AL
        - AK
        - AR
        - CA
        - CO
        - CT
        - DE
        - FL
        - GA
        - HI
        - ID
        - IL
        - IN
        - IA
        - KS
        - KY
        - LA
        - ME
        - MD
        - MA
        - MI
        - MN
        - MS
        - MO
        - MT
        - NE
        - NV
        - NH
        - NJ
        - NM
        - NY
        - NC
        - ND
        - OH
        - OK
        - OR
        - PA
        - RI
        - SC
        - SD
        - TN
        - TX
        - UT
        - VT
        - VA
        - WA
        - WV
        - WI
        - WY